USE [master]
GO

/****** Object:  Database [CAHUITA]    Script Date: 2/7/2018 11:08:28 ******/
CREATE DATABASE [CAHUITA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CAHUITA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CAHUITA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CAHUITA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CAHUITA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CAHUITA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CAHUITA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CAHUITA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CAHUITA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CAHUITA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CAHUITA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CAHUITA] SET ARITHABORT OFF 
GO

ALTER DATABASE [CAHUITA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CAHUITA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CAHUITA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CAHUITA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CAHUITA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CAHUITA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CAHUITA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CAHUITA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CAHUITA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CAHUITA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CAHUITA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CAHUITA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CAHUITA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CAHUITA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CAHUITA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CAHUITA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CAHUITA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CAHUITA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CAHUITA] SET  MULTI_USER 
GO

ALTER DATABASE [CAHUITA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CAHUITA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CAHUITA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CAHUITA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CAHUITA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CAHUITA] SET QUERY_STORE = OFF
GO

USE [CAHUITA]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CAHUITA] SET  READ_WRITE 
GO

USE [CAHUITA]
GO

/****** Object:  Table [dbo].[REGISTROS]    Script Date: 2/7/2018 11:09:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REGISTROS](
	[nombre] [varchar](20) NOT NULL,
	[apellido] [varchar](30) NOT NULL,
	[correo] [varchar](40) NOT NULL,
	[fecha_De_Nacimiento] [date] NOT NULL,
	[id] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [CAHUITA]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 2/7/2018 11:10:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[tipo] [varchar](15) NULL,
	[usuario] [varchar](45) NOT NULL,
	[contrasena] [varchar](40) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



